/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as PartnerApplyRouteImport } from './routes/partner.apply'
import { Route as OwnerRoomsRouteImport } from './routes/owner.rooms'
import { Route as OwnerCheckinRouteImport } from './routes/owner.checkin'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BookingRoomIdRouteImport } from './routes/booking.$roomId'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminHotelsRouteImport } from './routes/admin.hotels'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as DashboardBookingsBookingIdRouteImport } from './routes/dashboard.bookings.$bookingId'
import { Route as ApiPublicHooksReconcileKhaltiRouteImport } from './routes/api/public/hooks/reconcile-khalti'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/partner/apply',
  path: '/partner/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoomsRoute = OwnerRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCheckinRoute = OwnerCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRoute,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoomIdRoute = BookingRoomIdRouteImport.update({
  id: '/booking/$roomId',
  path: '/booking/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/admin/hotels',
  path: '/admin/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsBookingIdRoute =
  DashboardBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => DashboardBookingsRoute,
  } as any)
const ApiPublicHooksReconcileKhaltiRoute =
  ApiPublicHooksReconcileKhaltiRouteImport.update({
    id: '/api/public/hooks/reconcile-khalti',
    path: '/api/public/hooks/reconcile-khalti',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/owner': typeof OwnerRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/checkin': typeof OwnerCheckinRoute
  '/owner/rooms': typeof OwnerRoomsRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/api/public/hooks/reconcile-khalti': typeof ApiPublicHooksReconcileKhaltiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/checkin': typeof OwnerCheckinRoute
  '/owner/rooms': typeof OwnerRoomsRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/admin': typeof AdminIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/api/public/hooks/reconcile-khalti': typeof ApiPublicHooksReconcileKhaltiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/owner': typeof OwnerRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/checkin': typeof OwnerCheckinRoute
  '/owner/rooms': typeof OwnerRoomsRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/api/public/hooks/reconcile-khalti': typeof ApiPublicHooksReconcileKhaltiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/owner'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/requests'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/owner/bookings'
    | '/owner/checkin'
    | '/owner/rooms'
    | '/partner/apply'
    | '/payment/callback'
    | '/payment/failed'
    | '/admin/'
    | '/hotels/'
    | '/owner/'
    | '/dashboard/bookings/$bookingId'
    | '/api/public/hooks/reconcile-khalti'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/requests'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/owner/bookings'
    | '/owner/checkin'
    | '/owner/rooms'
    | '/partner/apply'
    | '/payment/callback'
    | '/payment/failed'
    | '/admin'
    | '/hotels'
    | '/owner'
    | '/dashboard/bookings/$bookingId'
    | '/api/public/hooks/reconcile-khalti'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/owner'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/requests'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/owner/bookings'
    | '/owner/checkin'
    | '/owner/rooms'
    | '/partner/apply'
    | '/payment/callback'
    | '/payment/failed'
    | '/admin/'
    | '/hotels/'
    | '/owner/'
    | '/dashboard/bookings/$bookingId'
    | '/api/public/hooks/reconcile-khalti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BookingRoomIdRoute: typeof BookingRoomIdRoute
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  PartnerApplyRoute: typeof PartnerApplyRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  ApiPublicHooksReconcileKhaltiRoute: typeof ApiPublicHooksReconcileKhaltiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/apply': {
      id: '/partner/apply'
      path: '/partner/apply'
      fullPath: '/partner/apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/rooms': {
      id: '/owner/rooms'
      path: '/rooms'
      fullPath: '/owner/rooms'
      preLoaderRoute: typeof OwnerRoomsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/checkin': {
      id: '/owner/checkin'
      path: '/checkin'
      fullPath: '/owner/checkin'
      preLoaderRoute: typeof OwnerCheckinRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$roomId': {
      id: '/booking/$roomId'
      path: '/booking/$roomId'
      fullPath: '/booking/$roomId'
      preLoaderRoute: typeof BookingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/admin/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings/$bookingId': {
      id: '/dashboard/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/dashboard/bookings/$bookingId'
      preLoaderRoute: typeof DashboardBookingsBookingIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/api/public/hooks/reconcile-khalti': {
      id: '/api/public/hooks/reconcile-khalti'
      path: '/api/public/hooks/reconcile-khalti'
      fullPath: '/api/public/hooks/reconcile-khalti'
      preLoaderRoute: typeof ApiPublicHooksReconcileKhaltiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OwnerRouteChildren {
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerCheckinRoute: typeof OwnerCheckinRoute
  OwnerRoomsRoute: typeof OwnerRoomsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerCheckinRoute: OwnerCheckinRoute,
  OwnerRoomsRoute: OwnerRoomsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface DashboardBookingsRouteChildren {
  DashboardBookingsBookingIdRoute: typeof DashboardBookingsBookingIdRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsBookingIdRoute: DashboardBookingsBookingIdRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OwnerRoute: OwnerRouteWithChildren,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BookingRoomIdRoute: BookingRoomIdRoute,
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  PartnerApplyRoute: PartnerApplyRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  AdminIndexRoute: AdminIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  ApiPublicHooksReconcileKhaltiRoute: ApiPublicHooksReconcileKhaltiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
